Relicense to LGPL
Lysxia/coq-simple-io pull request #51
Opened 2022-04-14 22:07 UTC by Lysxia

My understanding is there are no significant issues with switching to a less permissive license, but just as a matter of courtesy I'm pinging you contributors @liyishuai @gares @jjhugues to notify you of what's going on.

I just copied the `Uint63` module from Coq, so IIUC the whole library should be relicensed to LGPL. I heard there are plans to relicense Coq under a weaker license (MPL), and when that happens I'll probably revert back to MIT. The main reasons for copying this module are to recompile it without `-rectypes` (that is somehow used by Coq), and to get it from a less awkward-sounding place than `coq-core.kernel`.

2022-04-14 22:43 UTC, liyishuai requested changes

2022-04-14 22:43 UTC, liyishuai commented on dune-project
> +(license LGPL)
This should be a SPDX identifier.
```suggestion
(license LGPL-2.1-only)
```
I'm still asking for instructions: https://coq.zulipchat.com/#narrow/stream/237663-coq-community-devs-.26-users/topic/Advising.20against.20licenses.3F/near/279029933

2022-04-14 22:56 UTC, liyishuai submitted a review, later dismissed
Approving license change as a contributor; provided we figure out it's appropriate to do so.

2022-04-15 01:12 UTC, liyishuai commented
Based on the Zulip discussion, I'd propose licensing `Uint63`-related modules under LGPL, and declare the remainder of this library as dynamically linked to `Uint63`. Our minimal change is to add a copyright notice under the `extraction` directory.

2022-04-15 05:18 UTC, gares commented
My contribution is minor, do as you like

2022-04-16 00:00 UTC, jjhugues commented
My contribution is also a trivial one liner. No objection

2022-05-25 14:21 UTC, closed without merging